#Number of particles
N = 108
#Packing fraction or number densty. For a hard sphere system, the temperature (below) is zero, the density is interpreted as a packing fraction.
density = 0.4
#Lattice type options: sc, bcc, fcc, hcp. Stands for simple cubic, body-centered cubic, face-centered cubic, and hexagonal closest packed
lattice = "fcc"
#Temperature--set to zero for hard-sphere fluid
T = 0.0
#Timestep
dt = 0.001
#Initial stepsize for Monte Carlo
dr = 0.1
#Initial acceptance rate for Monte Carlo. Set to 0.3 according to the optimum found in 3.4.
acceptance = 0.3